import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'
import HeaderSection from '../components/Header'
import PersonSearchIcon from '@mui/icons-material/PersonSearch';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Chat 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <HeaderSection/>
        <Search>
          <PersonSearchIcon style={{marginLeft:'14px'}}/>
          <SearchInput placeholder="search in search"/>
        </Search>
        </Container>
    </div>
  )
}
export default Home

const Container = styled.div`
    margin: auto;
    width:50%;
    height:100vh;
    border:1px solid #F3F3F3;
`;

const Search = styled.div`
    display: flex;
    align-items: center;
    padding: 10px;
    border-radius: 2px;
    margin: auto;
    justify-content: center;
    background: #F3F3F3;
    width: 50%;
    margin-top: 29px;
`;
const SearchInput = styled.input`
    outline-width:0;
    border:none;
    background:#F3F3F3;
    padding:10px;
    outline:none;
    width:100%;
`;

